{{- if .Values.ingress.enabled -}}
{{- $hostname := .Values.ingress.host -}}
{{- $name := (index (splitList "." $hostname) 0) -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-ingress
  labels:
    app: {{ $name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ $hostname }}
    {{- if .Values.ingress.existingSecret }}
    secretName: {{ .Values.ingress.existingSecret }}
    {{- else if .Values.certificate.enabled }}
    secretName: {{ $name }}-tls
    {{- end }}
  {{- end }}
  rules:
  - host: {{ $hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}-service
            port:
              number: {{ .Values.service.port | default 9000 }}
{{- end }}

