{{- if not .Values.whisperx.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "whisperx-api.fullname" . }}
  labels:
    {{- include "whisperx-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  hf-token: {{ .Values.whisperx.hfToken | quote }}
{{- end }}

